name: creates original file

on:
    push:
        branches:
            - concurrence
    workflow_dispatch:

jobs:
    create-files:
        runs-on: ubuntu-latest
        concurrency:
            group: "file-modifier"
            cancel-in-progress: false # waits to do something
        steps:
            - uses: actions/checkout@v2
            - run: echo "file start" >> file.txt
            - name: upload file as artifact
              uses: actions/upload-artifact@v4
              with:
                name: file
                path: file.txt