name: read modified file

on:
    workflow_run:
        workflows: ["modifying file (first agent)","modifying file (second agent)"]
        types:
            - completed

jobs:
    read-file:
        runs-on: ubuntu-latest
        steps:
            - name: donwload file
              uses: actions/download-artifact@v4
              with:
                name: file
                github-token: ${{ secrets.GH_PAT }}
                repository: ${{ github.repository }}
                run-id: ${{ github.event.workflow_run.id }}
            - run: cat file.txt
            