name: Test if secret is "known"

on:
    push:
        branches:
            - secrets

jobs:
  secrets-if:
    runs-on: ubuntu-latest
    permissions:
        contents: read
    steps:
      - name: Testing if secret is known
        run: |
          if [ "$MY_SECRET" = "known"]; then
            echo "Secret is known"
          else
            echo "Secret is not known"

    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}