name: Test if secret is "known"

on:
    push:
        branches:
            - secrets

jobs:
  secrets-if:
    runs-on: ubuntu-latest
    steps:
      - name: Testing if secret is known
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          if [ "$MY_SECRET" = "known"]; then
            echo "Secret is known"
          elif "$MY_SECRET" = "***"]; then
            echo "Can't run ifs on secrets"
          else
            echo "Secret is not known"
          fi
