name: Test if secret is "known"

on:
    push:
        branches:
            - secrets

jobs:
  secrets-if:
    runs-on: ubuntu-latest
    permissions:
        contents: read
    steps:
      - name: Testing if secret is known
        if: ${{ env.MY_SECRET }} == 'known'
        run: echo "The secret is known."

      - name: Testing if secret is not known
        if: ${{ env.MY_SECRET }} != 'known'
        run: echo "The secret is not known"
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}